### ISSUE TITLE
pnpm install 后npm run dev编译出错

### ISSUE THREAD

**Issue by huangyuanyin** [Megasu/uniapp-shop-vue3-ts#2]
![image](https://github.com/Megasu/uniapp-shop-vue3-ts/assets/42410679/82bc1f8d-d379-4ee1-88d2-55797f17c062)

**Comment by Megasu** [comment]
你好，我这边不能复现您描述的问题，请尝试以下命令。

```sh
# 微信小程序端
npm run dev:mp-weixin

# H5端
npm run dev:h5
```
